# Generated by Django 4.1.1 on 2022-11-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0003_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcustomer',
            name='profile_pic',
        ),
    ]
