# Generated by Django 4.1.1 on 2022-11-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0004_remove_rcustomer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcustomer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rcustomer',
            name='name',
        ),
    ]
