# Generated by Django 4.1.1 on 2022-11-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0005_remove_rcustomer_email_remove_rcustomer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcustomer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
