# Generated by Django 4.1.1 on 2022-11-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0006_rcustomer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcustomer',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rcustomer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
