# Generated by Django 4.1.1 on 2022-11-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0007_rcustomer_email_rcustomer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('property_type', models.CharField(choices=[('Appartment', 'Appartment'), ('Duplex', 'Duplex'), ('Villa', 'Villa')], max_length=100)),
                ('length', models.CharField(max_length=200)),
                ('breadth', models.CharField(max_length=100)),
                ('Height', models.CharField(max_length=100)),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
