# Generated by Django 4.1.1 on 2022-11-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0009_delete_property_type_submit_date_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='submit',
            new_name='submit_order',
        ),
    ]
