# Generated by Django 4.1.1 on 2022-12-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0011_alter_submit_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_order',
            name='deleteStautus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rcustomer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to=''),
        ),
    ]
