# Generated by Django 4.1.1 on 2022-12-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0012_submit_order_deletestautus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submit_order',
            old_name='deleteStautus',
            new_name='delete_status',
        ),
    ]
