# Generated by Django 4.1.1 on 2022-12-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0013_rename_deletestautus_submit_order_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit_order',
            name='property_type',
            field=models.CharField(choices=[('Appartment', 'Appartment'), ('Duplex', 'Duplex'), ('Villa', 'Villa'), ('Beach House', 'Beach House'), ('Commercial Space', 'Commercial Space'), ('Rental', 'Rental')], max_length=100),
        ),
    ]
