# Generated by Django 4.1.1 on 2022-12-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0015_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_us',
        ),
    ]
